# -*- coding: utf-8 -*-
"""CO2_emisions_visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16_xE6jKej0yZbbL3PYxU6Xl3HxBoCPh5

# **Importing Libraries**
"""

!pip install darts

#python -m pip uninstall matplotlib
! pip install matplotlib==3.1.3

!pip install pyyaml==5.4.1

import pandas as pd
import plotly.express as px
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from darts import TimeSeries
from darts.models import *
from darts.metrics import *
from darts.dataprocessing.transformers import Scaler
import logging
import time

"""# Loading the data"""

co2_df = pd.read_csv('CO2_emission.csv')
co2_df.head()

"""# Geographical plotting world wide co2 emmission (metric tons per capita)"""

fig = px.choropleth(
    co2_df,
    locations="country_code",
    color="2010",
    hover_name="Country Name",
    hover_data=["2010"],
    title="CO2 Emission(metric tons per capita) Around the world in 2010",
    color_continuous_scale=px.colors.sequential.Oranges,
    
)
fig.update_geos(fitbounds="locations", visible=False)
fig.show()

fig = px.choropleth(
    co2_df,
    locations="country_code",
    color="2019",
    hover_name="Country Name",
    hover_data=["2019"],
    title="CO2 Emission(metric tons per capita) Around the world in 2019",
    color_continuous_scale=px.colors.sequential.Oranges,
    
)
fig.update_geos(fitbounds="locations", visible=False)
fig.show()

columns=np.arange(1990,2019).tolist()
columns_str = map(str,columns)
list_of_year = list(columns_str)
list_of_year

co2_region_df = co2_df.groupby('Region')[list_of_year].mean()
co2_region_df.index
co2_region_df

co2_region_df.unstack()

"""## Heat map for co2 emmission (metric tons per capita)-world wide"""

plt.figure(figsize=(16,16))
plt.rcParams['font.size'] = 10
plt.title("Mean CO2 Emissions in Different Rigions of earth(1990-2019)",fontweight="bold",fontdict={'fontsize': 30})
sns.heatmap(co2_region_df,linecolor='white',linewidths=1,annot=True)
plt.xlabel('Years',fontdict={'fontsize': 25})
plt.ylabel('Regions',fontdict={'fontsize': 25})



"""# Analysing the mathematical terms"""

co2_df.describe()

"""# Box plot of world wide	CO2 emissions (metric tons per capita)"""

df = pd.DataFrame(co2_region_df, columns = ['1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019'])
plt.rcParams["figure.figsize"] = [15, 7]
plt.rcParams["figure.autolayout"] = True
plt.xlabel('year', size=20)
plt.ylabel('CO2 emmision (metric tons per capita)',size=15)
plt.title('Box plot of world wide	CO2 emissions (metric tons per capita)')
df.boxplot()

a=co2_df['Region']
b=co2_df.columns[3:]
print(a,b)

co2_region_df.head()

new_Co2=co2_region_df.T
new_Co2.head()



df = pd.DataFrame(new_Co2, columns = ['Europe & Central Asia','East Asia & Pacific','Latin America & Caribbean','Middle East & North Africa','North America','South Asia','Sub-Saharan Africa'])
plt.rcParams["figure.figsize"] = [15, 10]
plt.rcParams["figure.autolayout"] = True
plt.xlabel('Region',size=20)
plt.ylabel('CO2 emmision (metric tons per capita)',size=15)
plt.title('Box plot of world wide	CO2 emissions (metric tons per capita)')
df.boxplot()

"""## Visualizing a perticular region data
Loading data of Afganistan (south asia)_co2 emmision (metric tons per capita)
"""

new_df=pd.read_excel('AFG_CO2_DATA.xlsx')

new_df.head()

"""# Bar plot of Afghanistan (South Asia)	CO2 emissions (metric tons per capita)"""



plt.bar(new_df['year'], new_df['AFG_CO2_emmision'])
plt.xlabel('year',size=20)
plt.ylabel('CO2 emmision (metric tons per capita)',size=15)

plt.title('Bar plot of Afghanistan (South Asia)	CO2 emissions (metric tons per capita)')
plt.show()

"""## Box plot of Afghanistan (South Asia)	CO2 emissions (metric tons per capita)"""

df = pd.DataFrame(new_df, columns = ['year'])
plt.rcParams["figure.figsize"] = [15, 7]
plt.rcParams["figure.autolayout"] = True
plt.xlabel('year',size=20)
plt.ylabel('CO2 emmision (metric tons per capita)',size=15)
plt.title('Box plot of Afghanistan (South Asia)	CO2 emissions (metric tons per capita)')
df.boxplot()
plt.show()

EAP_CO2=new_Co2["East Asia & Pacific"]

EAP_CO2_df= EAP_CO2.to_frame()

print(EAP_CO2_df.columns)

EAP_CO2_df['year'] = EAP_CO2_df.index
EAP_CO2_df.head()



EAP_CO2_df.shape



series = TimeSeries.from_dataframe(EAP_CO2_df, time_col='year')

series.plot()